app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

# bundles routings
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}

fos_user_registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

api:
    resource: "@AppBundle/Controller/TaskApiController.php"
    prefix:   /api
    type:     rest
    options:  { expose: true }
