services:
    data_collector.tasks:
        class: AppBundle\Collector\TaskDataCollector
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: data_collector, template: 'collectors/tasks.html.twig', id: 'tasks' }

